env: dev
namespace: dev
host: dev-app.webhop.me
image:
  repository: budcalmy/task18-nginx
  tag: latest
names:
  app: nginx
  configmap: nginx-html-configmap
  deployment: nginx-deployment
  service: nginx-service
  secret: nginx-config-secret
  tlsSecret: nginx-tls-secret
  ingress: nginx-ingress
