# Default values for the NGINX chart
env: dev
namespace: dev
host: nginx.webhop.me
names:
  app: dev-nginx
  configmap: dev-nginx-html-configmap
  deployment: dev-nginx-deployment
  service: dev-nginx-service
  secret: dev-nginx-secret
  certificate: dev-nginx-certificate
  ingress: dev-nginx-ingress
