env: dev
namespace: dev
host: dev-app.webhop.me
names:
  app: nginx
  configmap: nginx-html-configmap
  deployment: nginx-deployment
  service: nginx-service
  secret: nginx-config-secret
  tlsSecret: nginx-tls-secret
  certificate: nginx-certificate
  ingress: nginx-ingress
